- README.md
- Added ize installation info via hombrew
> Add ize installation info to MacOS via Homebrew (TOOLS-78)

- go.mod
- go.sum
- internal/commands/base.go
- internal/commands/base_init.go
- internal/commands/helpers.go
- internal/commands/helpers_test.go
- internal/commands/terraform.go
This commits adds:
- external tools validation 
- installing SSM Agent automatically 
Example: 
Windows 11 SSM Agent
Ubuntu (wsl2) SSM Agent
[![asciicast](https://asciinema.org/a/6LgGPojgEgBlNsAykFwnoUvBt.svg)](https://asciinema.org/a/6LgGPojgEgBlNsAykFwnoUvBt)
Ubuntu (wsl2) Docker
[![asciicast](https://asciinema.org/a/8IozlqwC52HZ3Nt8qWBhlwrFO.svg)](https://asciinema.org/a/8IozlqwC52HZ3Nt8qWBhlwrFO)
Windows 11 Docker
> TOOLS-72 TOOLS-75 external tools validation

- .github/workflows/build_on_release.yml
- .goreleaser.yml
- Replaced go builder with GoReleaser on release
> Add GoReleaser to github workflow (TOOLS-85)

- internal/commands/base.go
- internal/commands/version.go
This commit adds a flag for print IZE version
> TOOLS-92 add version flag

- .github/workflows/build_on_release.yml
- .goreleaser.yml
- README.md
- Added deb package of ize creation to GoReleaser workflow
- Added upload of deb package to Gemfury.io repo (https://apt.fury.io/hazelops/)
- Added instruction of how to install ize on linux using public repo
Installation from repo:
Upgrade from repo:
> Add deb package creation, upload to fury.io and Ubuntu apt installation documentation (TOOLS-84)

- internal/commands/base.go
- internal/commands/mfa.go
- add mfa export command
[![asciicast](https://asciinema.org/a/w7aadvsPmY3WjKAK1TR9zddGX.svg)](https://asciinema.org/a/w7aadvsPmY3WjKAK1TR9zddGX)
> TOOLS-90 add mfa export command

- internal/commands/terraform/terraform.go
- fix get terraform version from env
[![asciicast](https://asciinema.org/a/tbJUWUkQ0cLhCvxtTSVkS3ehd.svg)](https://asciinema.org/a/tbJUWUkQ0cLhCvxtTSVkS3ehd)
> TOOLS-173 fix get terraform version from env

- internal/config/config.go
Add ability to read the following env vars:
- ENV
- AWS_PROFILE
- AWS_REGION
- NAMESPACE
In addition to `IZE_*` prefixed-ones
[![asciicast](https://asciinema.org/a/YMnmXJyZWPapavZOb8hvufFS0.svg)](https://asciinema.org/a/YMnmXJyZWPapavZOb8hvufFS0)
> Main environment parameters read from conventional env vars (TOOLS-186)

- internal/commands/ize.go
- Changed path to docs in the welcome message
> Change Docs path (TOOLS-184)

- internal/commands/tunnel/tunnel.go
- fix ize tunnel handle args
[![asciicast](https://asciinema.org/a/AFk2XS1wqMzw6SNIbRi2jPTLr.svg)](https://asciinema.org/a/AFk2XS1wqMzw6SNIbRi2jPTLr)
> TOOLS-212 fix ize tunnel handle args

- internal/commands/console/console.go
- internal/commands/deploy/deploy.go
- internal/commands/deploy/deploy_infra.go
- internal/commands/destroy/destroy_infra.go
- internal/commands/env/env.go
- internal/commands/gendoc.go
- internal/commands/initialize/initialize.go
- internal/commands/ize.go
- internal/commands/mfa/mfa.go
- internal/commands/secrets/secrets_edit.go
- internal/commands/secrets/secrets_push.go
- internal/commands/secrets/secrets_rm.go
- internal/commands/terraform/terraform.go
- internal/commands/tunnel/tunnel.go
- internal/commands/tunnel/tunnel_down.go
- internal/commands/tunnel/tunnel_sshkey.go
- internal/commands/tunnel/tunnel_status.go
- internal/commands/tunnel/tunnel_up.go
- silence usage msgs when usage was valid
[![asciicast](https://asciinema.org/a/tNojjIbkwQMK8OYwlL4dbGYD5.svg)](https://asciinema.org/a/tNojjIbkwQMK8OYwlL4dbGYD5)
> TOOLS-155 silence usage msgs when usage was valid

- .github/workflows/build_on_release.yml
- Added markdown to html convertor (uses https://github.com/marketplace/actions/markdown-to-pdf-and-html)
(Styles coud be added through css file)
- Changed destination of document files to `docs` in ize.sh repo
> Add md to html converter (TOOLS-183)

- internal/commands/config/config.go
- internal/commands/ize.go
- internal/config/config.go
- add a command to create a global configuration
- add global configuration readings
Сonfiguration read priority order:
- the set path to the configuration
- the place of the IZE call
- environment directory
- if env and namespace are specified then the global configuration
[![asciicast](https://asciinema.org/a/7zKrObahDbEPlk62999oauxG2.svg)](https://asciinema.org/a/7zKrObahDbEPlk62999oauxG2)
> TOOLS-218 global config with order of precedence

- internal/commands/console/console.go
- internal/commands/exec/exec.go
- Changed `Getting running task` to `Accessing container` everywhere
> Language updated (IZE-216)

- go.mod
- go.sum
- containerd version 1.5.10 is locked down
not required
> IZE-240 containerd version is locked down

- internal/commands/console/console_test.go
- fix tests for console commands
```
go tool cover -func cover.out                       
github.com/hazelops/ize/internal/commands/console/console.go:22:        NewConsoleFlags 100.0%
github.com/hazelops/ize/internal/commands/console/console.go:26:        NewCmdConsole   93.3%
github.com/hazelops/ize/internal/commands/console/console.go:60:        Complete        87.5%
github.com/hazelops/ize/internal/commands/console/console.go:77:        Validate        100.0%
github.com/hazelops/ize/internal/commands/console/console.go:92:        Run             88.9%
total:                                                                  (statements)    91.4%
```
> IZE-241 fix tests for console commands

- internal/config/config.go
- fix inconsistent interval between log level and file name
> IZE-277 fix inconsistent interval between

- internal/commands/ize.go
- internal/config/config.go
- set namespace as required
```
psih@DESKTOP-BGN2VJK:~/go/src/github.com/psihachina/ize/examples/simple-monorepo$ ize tunnel
✗ can't configure tunnel: namespace must be specified using flags, env or config file
psih@DESKTOP-BGN2VJK:~/go/src/github.com/psihachina/ize/examples/simple-monorepo$ ize -h
Opinionated tool for infrastructure and code.
This tool is designed as a simple wrapper around popular tools,
so they can be easily integrated in one infra: terraform,
ECS deployment, serverless, and others.
It combines infra, build and deploy workflows in one
and is too simple to be considered sophisticated.
So let's not do it but rather embrace the simplicity and minimalism.
Usage:
ize [flags]
ize [command]
Available Commands:
completion  Generate the autocompletion script for the specified …
```
> IZE-273 set namespace as required

- internal/commands/ize.go
- hide help command
```
psih  ~/go/src/github.com/psihachina/ize   IZE-275-help-command-not-flag-is-inconsistent  ize   
Welcome to IZE
Docs: https://ize.sh/docs
Version: development
Opinionated tool for infrastructure and code.
This tool is designed as a simple wrapper around popular tools,
so they can be easily integrated in one infra: terraform,
ECS deployment, serverless, and others.
It combines infra, build and deploy workflows in one
and is too simple to be considered sophisticated.
So let's not do it but rather embrace the simplicity and minimalism.
Usage:
ize [flags]
ize [command]
Available Commands:
completion  Generate the autocompletion script for the specified shell
config      generate global config
console     connect to a container in the ECS
deploy      manage …
```
> IZE-275 hide help command

- internal/commands/deploy/deploy.go
- internal/commands/deploy/deploy_infra.go
(Cancelled) deploy:
```
» [dev] Running deploy infra...
» Execution terraform init...
❌ running terraform v1.1.3...
│ 2022-04-15T21:22:00.775+0100 [INFO]  Terraform version: 1.1.3
│ 2022-04-15T21:22:00.775+0100 [INFO]  Go runtime version: go1.17.2
│ 2022-04-15T21:22:00.775+0100 [INFO]  CLI args: []string{"/Users/dmitry/.ize/vers
│ ions/terraform/terraform_1.1.3", "init", "-input=true"}
```
> Fixes IZE-244: Adds environment name to infra deployment header.

- internal/commands/version.go
- make ize version similar to ize --version
```
psih@DESKTOP-BGN2VJK:~/go/src/github.com/psihachina$ ize -v
ize version development
psih@DESKTOP-BGN2VJK:~/go/src/github.com/psihachina$ ize version
ize version development
```
> make ize version similar to ize --version

- internal/commands/terraform/terraform.go
- internal/config/config.go
- send username in terraform container
```
Acquiring state lock. This may take a few moments...
╷
│ Error: Error acquiring the state lock
│
│ Error message: ConditionalCheckFailedException: The conditional request failed
│ Lock Info:
│   ID:        e7238e11-4d2d-c6df-40fa-7465ed544548
│   Path:      nutcorp-tf-state/dev/terraform.tfstate
│   Operation: OperationTypeApply
│   Who:       psih@fe316c6622fb
│   Version:   1.1.3
│   Created:   2022-04-19 07:49:58.560120729 +0000 UTC
│   Info:
│
│
│ Terraform acquires a state lock to protect the state from being written
│ by multiple users at the same time. Please resolve the issue above and try
│ again. For most commands, you can disable locking with the "-lock=false"
│ flag, but this is not recommended.
╵
✗  container exit status code 1
```
> IZE-293 send username in terraform container

- .github/workflows/create_dev_release.yml
- Only one build could be run for DEV releases
When a concurrent job or workflow is queued, if another job or workflow using the same concurrency group in the repository is in progress, the queued job or workflow will be pending. 
Any previously pending job or workflow in the concurrency group will be canceled
> Only one build could be run for DEV releases (IZE-299)

- internal/commands/tunnel/tunnel.go
- internal/commands/tunnel/tunnel_down.go
- internal/commands/tunnel/tunnel_up.go
- add a pathError handler to tunnel command
[![asciicast](https://asciinema.org/a/uGRSroLxfws4O7NGnEtLExH0D.svg)](https://asciinema.org/a/uGRSroLxfws4O7NGnEtLExH0D)
> IZE-306 add a pathError handler to tunnel command

- .github/workflows/build_on_push.yml
- .github/workflows/build_on_release.yml
- .goreleaser.yml
- .goreleaser_push.yml
- Makefile
- internal/commands/ize.go
- internal/commands/status/status.go
- internal/commands/version.go
- internal/version/version.go
- add version package
- add git SHA to goreleaser
- add status command
```
AWS: default psih  ~  ize status
⚠  could not run git rev-parse, the default tag was set: dev
ENV              | dev
TAG              | dev
INFRA DIR        | /home/psih/.ize
PWD              | /home/psih
IZE VERSION      | development
IZE GIT REVISION | ec181a0+CHANGES
ENV DIR          | /home/psih/.ize/nutcorp/dev
OS   | linux
ARCH | amd64
AWS_DEV_ENV_NAME |
AWS PROFILE      | dev-nutcorp
AWS USER         | nikita
AWS ACCOUNT      | xxxxxxxxxxx
```
```
AWS: default psih  ~/go/src/github.com/psihachina/nutcorp-backend   develop ±  ize status
ENV              | dev
TAG              | 1e40ac8
INFRA DIR        | /home/psih/go/src/github.com/psihachina/nutcorp-backend/.infra
PWD              | …
```
> IZE-282 ability to show troubleshooting information

- examples/bastion-tunnel-monorepo/.ize/env/testnut/ize.toml
- examples/ecs-apps-monorepo/.ize/env/testnut/ize.toml
- internal/commands/tunnel/tunnel.go
- internal/commands/tunnel/tunnel_up.go
- test-e2e/bastion_tunnel_test.go
- test-e2e/ecs_apps_test.go
- test-e2e/terraform_test.go
- test-e2e/util.go
- add e2e test of bastion tunnel monorepo
- add aws_profile to basion tunnel monorepo
- some fixes
```
psih ~ go test -v --timeout 0 --tags "e2e bastion_tunnel" ./test-e2e 
=== RUN   TestIzeGenEnv_bastion_tunnel
--- PASS: TestIzeGenEnv_bastion_tunnel (4.17s)
=== RUN   TestIzeDeployAll_bastion_tunnel
--- PASS: TestIzeDeployAll_bastion_tunnel (189.39s)
=== RUN   TestIzeTunnelUp
--- PASS: TestIzeTunnelUp (14.99s)
=== RUN   TestIzeTunnelStatus
--- PASS: TestIzeTunnelStatus (3.21s)
=== RUN   TestIzeTunnelDown
--- PASS: TestIzeTunnelDown (3.41s)
=== RUN   TestIzeDestroyAll_bastion_tunnel
--- PASS: TestIzeDestroyAll_bastion_tunnel (175.68s)
PASS
ok      github.com/hazelops/ize/test-e2e        390.843s```
> IZE-313 test ize tunnel up down status

- go.mod
- go.sum
> Revert "Bump github.com/aws/aws-sdk-go from 1.44.24 to 1.44.25"

- Makefile
- internal/commands/status/status.go
- internal/config/config.go
- Update ize install so it doesn't store binary in the root
- Update order of calling AWS Auth
- Show actual aws profile that is passed
- Improve AWS status errors
- Use PREFER_RUNTIME in viper as a base value
```
❯ ize status
ENV            | testnut
NAMESPACE      |
TAG            | 78357b4
INFRA DIR      | /Users/dmitry/dev/hazelops/ize/examples/ecs-apps-monorepo/.ize
PWD            | /Users/dmitry/dev/hazelops/ize/examples/ecs-apps-monorepo
IZE VERSION    | development
GIT REVISION   | 78357b4+CHANGES
ENV DIR        | /Users/dmitry/dev/hazelops/ize/examples/ecs-apps-monorepo/.ize/env/testnut
PREFER_RUNTIME | native
TERRAFORM_VERSION | 1.1.7
OS   | darwin
ARCH | amd64
AWS PROFILE | nutcorp-dev
AWS USER    | dmitry
AWS ACCOUNT | <redacted>
AWS_DEV_ENV_NAME | dmitry
```
> Status fixes

- internal/commands/initialize/initialize.go
- internal/generate/generate.go
- add success message to ize init command
[![asciicast](https://asciinema.org/a/EMeHmAtGOktY2iDUBwMR7Pv3s.svg)](https://asciinema.org/a/EMeHmAtGOktY2iDUBwMR7Pv3s)
> IZE-342 add success message to ize init command

- internal/commands/gen/env.go
- move terraform state bucket name and region to infra terraform under infra terraform
[![asciicast](https://asciinema.org/a/dzpiIYhYcqeZHXgzyL66rnPvL.svg)](https://asciinema.org/a/dzpiIYhYcqeZHXgzyL66rnPvL)
> IZE-337 move terraform state bucket name and region

- .github/workflows/run-tests.yml
- examples/bastion-tunnel-monorepo/.ize/env/testnut/ize.toml
- examples/ecs-apps-monorepo/.ize/env/testnut/ize.toml
- go.mod
- go.sum
- internal/commands/status/status.go
- internal/commands/tunnel/tunnel.go
- internal/commands/tunnel/tunnel_down.go
- internal/commands/tunnel/tunnel_up.go
- internal/config/config.go
- test-e2e/bastion_tunnel_test.go
- test-e2e/ecs_apps_test.go
- test-e2e/terraform_test.go
- fix overwriting `ENV` environment variable by env in ize.toml
- set `max-parallel` value to 1
- update test run command
- fix `IZE_EXAMPLES_PATH` environment variable in bastion tunnel test
- remove `ENV` variable from config file
- update ssh command building in `tunnel` and `tunnel up` commands
- update `terraform-switcher` version
- rename `env` command to `tfenv` command in tests
- rename `deploy` command to `up` command in tests
- rename `destroy` command to `down` command in tests
- update tests to to non-docker runtime
[![asciicast](https://asciinema.org/a/WaRdT7NU15yv3uHyeU6kc0elA.svg)](https://asciinema.org/a/WaRdT7NU15yv3uHyeU6kc0elA)
> IZE-367 IZE-382 IZE-381 tests updated

- test-e2e/ecs_apps_test.go
- fix apps urls
```
=== RUN   TestIzeGenEnv_ecs_apps
--- PASS: TestIzeGenEnv_ecs_apps (2.95s)
=== RUN   TestIzeSecretsPushGoblin
--- PASS: TestIzeSecretsPushGoblin (5.68s)
=== RUN   TestIzeSecretsPushSquibby
--- PASS: TestIzeSecretsPushSquibby (5.69s)
=== RUN   TestIzeUpAll_ecs_apps
--- PASS: TestIzeUpAll_ecs_apps (359.04s)
=== RUN   TestIzeExecGoblin
--- PASS: TestIzeExecGoblin (6.54s)
=== RUN   TestCheckSecretsSquibby
--- PASS: TestCheckSecretsSquibby (1.81s)
=== RUN   TestCheckSecretsGoblin
ecs_apps_test.go:257: The expected string was not found in the response: http://squibby.test-ecs-apps.examples.ize.sh/
--- FAIL: TestCheckSecretsGoblin (52.73s)
=== RUN   TestIzeDownAll_ecs_apps
--- PASS: TestIzeDownAll_ecs_apps (392.16s)
FAIL
FAIL    github.com/hazelops/ize/test-e2e        826.608s …
```
> IZE-376 fix apps urls

- internal/config/config.go
- internal/schema/ize-spec.json
- bind `TAG` env to `IZE_TAG` env
- change the order of required parameters in json shema
- move settings tag parameter after init config
[![asciicast](https://asciinema.org/a/UWXi6PM7UtC8mlAj1EBmFsibJ.svg)](https://asciinema.org/a/UWXi6PM7UtC8mlAj1EBmFsibJ)
> IZE-416 IZE-418 IZE-419 able to read tag env var in addition to ize tag

- internal/commands/console/console.go
- internal/commands/exec/exec.go
- add `container-name` flag to `console` and `exec` commands
[![asciicast](https://asciinema.org/a/BcGhNWi1UltRwUSDhMhUYZJWr.svg)](https://asciinema.org/a/BcGhNWi1UltRwUSDhMhUYZJWr)
> IZE-415 add `container-name` flag to `console` and `exec` commands

- internal/config/config.go
- internal/schema/ize-spec.json
- add `terraform_version` parameter with backward compatibility
[![asciicast](https://asciinema.org/a/2U0EtR5QEpaep90AIp1mZTC5x.svg)](https://asciinema.org/a/2U0EtR5QEpaep90AIp1mZTC5x)
> IZE-397 add `terraform_version` parameter with backward compatibility

- internal/manager/serverless/native.go
This fixes a typo where node version was not used.
> IZE-508: Fix typo

- internal/commands/tfenv.go
- internal/config/config.go
- internal/config/infra.go
- internal/schema/ize-spec.json
> Added state_name so it allows to set the name of the state file.

- examples/README.md
> Update Readme.md (IZE-522)

- internal/commands/build.go
- internal/commands/ize.go
- internal/docker/builder.go
- internal/docker/registry.go
- internal/manager/ecs/ecs.go
- add amd64 platform by default
> add amd64 platform by default

- internal/commands/doc.go
- internal/commands/exec.go
- internal/commands/ize.go
- fixed handling of missing commands
- fixed detection of env parameter in 'ize terraform` command
- fixed command documentation generation
[![asciicast](https://asciinema.org/a/4wmGgisJIJVAwlmLgyYwhTUnt.svg)](https://asciinema.org/a/4wmGgisJIJVAwlmLgyYwhTUnt)
[![asciicast](https://asciinema.org/a/Ob3qPhGsyhPNlzwORZvCnw6KW.svg)](https://asciinema.org/a/Ob3qPhGsyhPNlzwORZvCnw6KW)
[![asciicast](https://asciinema.org/a/oBkLr4pcqri0RNv8lmFNgdfmN.svg)](https://asciinema.org/a/oBkLr4pcqri0RNv8lmFNgdfmN)
> IZE-585 IZE-577 IZE-580 invalid ize exec command not handled

- examples/ecs-apps-monorepo/.ize/env/testnut/goblin.tf
- examples/ecs-apps-monorepo/.ize/env/testnut/squibby.tf
- internal/terraform/local.go
- internal/terraform/terraform_test.go
- added unit tests for the `terraform` package
> added unit tests for the `terraform` package

- internal/manager/serverless/serverless_test.go
- added unit tests for the serverless manager
> IZE-576 Added unit tests for the serverless manager

- .github/workflows/run.e2e-tests.yml
- examples/ecs-apps-monorepo/.ize/env/testnut/ize.toml
- internal/commands/down.go
- internal/commands/tfenv.go
- internal/commands/tfenv_test.go
- internal/template/template.go
- changed generation of tfvars file taking into account ecs apps
[![asciicast](https://asciinema.org/a/hS77UJumDdi9Kpj8H4wLwdwce.svg)](https://asciinema.org/a/hS77UJumDdi9Kpj8H4wLwdwce)
> IZE-511 changed generation of tfvars file taking into account ecs apps

- internal/commands/down.go
- internal/commands/down_infra.go
added call `terraform init` before `terraform destroy` in `ize down`/`ize down infra` commands
[![asciicast](https://asciinema.org/a/AVW2OSIUZ6bl3oJMR70oFsXAk.svg)](https://asciinema.org/a/AVW2OSIUZ6bl3oJMR70oFsXAk)
> IZE-599 ize infra down doesnt run terraform init

- go.mod
- go.sum
- internal/schema/ize-spec.json
- internal/schema/schema.go
added new jsonschema validator
Old validator unsupported new drafts and bad handle errors.
[![asciicast](https://asciinema.org/a/qbTJUivcxnxe7EsTWHUD90QXq.svg)](https://asciinema.org/a/qbTJUivcxnxe7EsTWHUD90QXq)
> IZE-581 Missing parameters showed at once

- internal/commands/doc.go
- internal/schema/ize-spec.json
- internal/schema/schema.go
added generation of markdown files with IZE specification
[![asciicast](https://asciinema.org/a/RiV0MZx8pg51Fbnh2D3Zbuty8.svg)](https://asciinema.org/a/RiV0MZx8pg51Fbnh2D3Zbuty8)
| Parameter | Required | Description |
| --- | --- | --- |
| aws_profile | no | (optional) ECS-specific AWS profile (optional) can be specified here (but normally it should be inherited from a global AWS_PROFILE). |
| aws_region | no | (optional) ECS-specific AWS Region of this environment should be specified here. Normally global AWS_REGION is used. |
| cluster | no | (optional) ECS cluster can be specified here. By default it's derived from env & namespace |
| depends_on | no | (optional) expresses startup and shutdown dependencies between apps |
| docker_registry | no | (optional) Docker registry can be set …
> IZE-598 added generation of markdown files with IZE specification

- internal/commands/up.go
- internal/config/project.go
- internal/config/project_test.go
added multiple deploy apps\stacks
[![asciicast](https://asciinema.org/a/TRpqxkjXQRuwcf3FEmr9tDLkU.svg)](https://asciinema.org/a/TRpqxkjXQRuwcf3FEmr9tDLkU)
> IZE-616 added multiple deploy apps\stacks

- internal/manager/ecs/ecs_test.go
- internal/manager/ecs/native.go
- added overwriting docker image name and tag in native ECS deployment
[![asciicast](https://asciinema.org/a/0aR7H7Nn6OwfinBp6NCasoZPV.svg)](https://asciinema.org/a/0aR7H7Nn6OwfinBp6NCasoZPV)
> IZE-648 Overwrite docker image name and tag when the most recent task definition is used

- internal/schema/schema.go
added display of possible properties when ize.toml has invalid syntax
[![asciicast](https://asciinema.org/a/RUSXCH2y0mGNjaAvRAhc7w9j8.svg)](https://asciinema.org/a/RUSXCH2y0mGNjaAvRAhc7w9j8)
> IZE-487 added display of possible properties when ize.toml has invalid syntax

- internal/commands/ize.go
- internal/commands/logs.go
- internal/commands/start.go
- internal/config/config.go
added `ize start <app_name>` command
[![asciicast](https://asciinema.org/a/SpMXDkca7H2oUHzg0kdHoplkQ.svg)](https://asciinema.org/a/SpMXDkca7H2oUHzg0kdHoplkQ)
> IZE-592 IZE-665 start ecs task

- internal/commands/tunnel_up.go
added `use-e2-metadata` flag
[![asciicast](https://asciinema.org/a/Qa4h2HLmx8GFft8VHwmGNbvi2.svg)](https://asciinema.org/a/Qa4h2HLmx8GFft8VHwmGNbvi2)
> IZE-669 added `use-e2-metadata` flag

- internal/commands/doc.go
disabled pterm style when generation markdown
[![asciicast](https://asciinema.org/a/dhGrovwPgQr6DVXXeXnmdsLzl.svg)](https://asciinema.org/a/dhGrovwPgQr6DVXXeXnmdsLzl)
> IZE-675 disabled pterm style when generation markdown

- internal/commands/tfenv.go
- internal/config/infra.go
- internal/schema/ize-spec.json
- internal/template/template.go
added `terraform_config_file` parameter
[![asciicast](https://asciinema.org/a/I0KJLFJBdvZ3v0zHBW9IbXDz9.svg)](https://asciinema.org/a/I0KJLFJBdvZ3v0zHBW9IbXDz9)
> IZE-509 added `terraform_config_file` parameter

- internal/commands/tunnel_up.go
added command and pid display when the port is busy
[![asciicast](https://asciinema.org/a/o6FkgurtoqtLCcZJ8crYnCXFa.svg)](https://asciinema.org/a/o6FkgurtoqtLCcZJ8crYnCXFa)
> IZE-524 added command and pid display when the port is busy

- internal/commands/ize.go
- internal/commands/nvm.go
- internal/manager/serverless/native.go
- internal/manager/serverless/serverless.go
added `ize nvm` command
[![asciicast](https://asciinema.org/a/Lztb6N3YVRbTMGjhdWg8XWdYn.svg)](https://asciinema.org/a/Lztb6N3YVRbTMGjhdWg8XWdYn)
> IZE-659 added `ize nvm` command

- examples/multistack-monorepo/ize.toml
- examples/multistack-monorepo/s3/main.tf
- examples/multistack-monorepo/s3/variables.tf
- examples/multistack-monorepo/variables.tf
- examples/multistack-monorepo/vpc/main.tf
- examples/multistack-monorepo/vpc/variables.tf
> Multistack example - vpc, s3 (ize-445)

- test-e2e/bastion_tunnel_test.go
- test-e2e/ecs_apps_test.go
- test-e2e/terraform_test.go
added output display when debug mode is enabled
> IZE-621 added output display when debug mode is enabled

- internal/commands/tunnel_down.go
- internal/commands/tunnel_status.go
- internal/commands/tunnel_up.go
added explain mode for `ize tunnel` commands
[![asciicast](https://asciinema.org/a/HQxghA8BuIuunhxbQcKxo1keI.svg)](https://asciinema.org/a/HQxghA8BuIuunhxbQcKxo1keI)
> IZE-682 added explain mode for `ize tunnel` commands

- examples/ecs-apps-monorepo/.ize/env/testnut/squibby.tf
- internal/commands/tunnel_up.go
- internal/commands/tunnel_up_test.go
`strict-host-key-checking` parameter is inverted
[![asciicast](https://asciinema.org/a/gdB8QGkaMXtqKjdemMjveSTrR.svg)](https://asciinema.org/a/gdB8QGkaMXtqKjdemMjveSTrR)
> `strict-host-key-checking` parameter is inverted

- internal/commands/tunnel_up.go
added check of a pre-existing bastion.sock
[![asciicast](https://asciinema.org/a/uKM5MiNnpa1coRTbj6egrbHUN.svg)](https://asciinema.org/a/uKM5MiNnpa1coRTbj6egrbHUN)
[![asciicast](https://asciinema.org/a/3K5bKtlWYFzr5cL1ArgKIMrKR.svg)](https://asciinema.org/a/3K5bKtlWYFzr5cL1ArgKIMrKR)
> IZE-688 added check of a pre-existing bastion.sock

- internal/commands/logs.go
added `task` flag
[![asciicast](https://asciinema.org/a/raNQ2T7C1i6Ykinl7wnpI50D9.svg)](https://asciinema.org/a/raNQ2T7C1i6Ykinl7wnpI50D9)
> IZE-707 added `task` flag

- internal/commands/secrets_pull.go
- internal/commands/secrets_push.go
- internal/commands/secrets_rm.go
added explain for `ize secrets pull|push|rm`
[![asciicast](https://asciinema.org/a/cnqQBBtWQ3M32QHJ8EuduYHmQ.svg)](https://asciinema.org/a/cnqQBBtWQ3M32QHJ8EuduYHmQ)
> IZE-696 added explain for `ize secrets pull|push|rm`

- internal/commands/exec.go
added explain for `ize exec`
[![asciicast](https://asciinema.org/a/BYIVDHZLMjMWCbK0NJPa3ZtDk.svg)](https://asciinema.org/a/BYIVDHZLMjMWCbK0NJPa3ZtDk)
> IZE-698 added explain for `ize exec`

- internal/commands/tunnel_up.go
passed aws region via an env var for up tunnel
> IZE-722 passed aws region via an env var for up tunnel

- pkg/ssmsession/ssmsession.go
- tests/e2e/ecs_apps_test.go
fixed work ssm-plugin in non-interactive environment
[![asciicast](https://asciinema.org/a/riIUOTrsvlk8kZQKR3nQWX3nH.svg)](https://asciinema.org/a/riIUOTrsvlk8kZQKR3nQWX3nH)
> fixed work ssm-plugin in non-interactive env

- internal/commands/deploy.go
- internal/config/app.go
- internal/manager/serverless/native.go
- internal/schema/ize-spec.json
added `force` flag for sls deploy
[![asciicast](https://asciinema.org/a/P4mEichl3BxM2DJvwQDP9gptz.svg)](https://asciinema.org/a/P4mEichl3BxM2DJvwQDP9gptz)
> IZE-687 added `force` flag for sls deploy

- .github/workflows/run.apt-install-tests.yml
- .github/workflows/run.brew-install-tests.yml
- added brew install test
- added apt install test
Brew:
APT:
> IZE-380 Install tests

- .github/workflows/release-dev.build-and-publish.yml
- .github/workflows/release-prod.build-and-publish.yml
- .goreleaser.yml
- .goreleaser_push.yml
- Goreleaser action updated
- Settings for Goreleaser updated
- Go installer action is updated
> IZE-776 Goreleaser & Go installer updated

- .github/workflows/release-prod.build-and-publish.yml
- Added homebrew rb file numbered version creation
- Get ize.rb file (with latest version of ize) and copy it to the temp folder
- Get version of release from 'version' in rb.ize(in temp folder)
- remove dots from 'version'  and copy it to variable
- add version without dots to the copied rb.ize file (in temp folder)
- rename ize.rb to ize-<version>.rb (in temp folder)
- commit ize-<version>.rb to the hazelops/homebrew-ize repo
Repo:
Changes in the file:
> IZE-645 ize homebrew version automated
