hazelops/ize

.github/workflows/build_on_release.yml
.goreleaser.yml
README.md

- Added Homebrew to GoReleaser
- Added version creation in ize binary
- Ize binary gets version from release tag

Add Homebrew to GoReleaser and version to ize binary (TOOLS-85, TOOLS-93)

---

internal/commands/base.go
internal/commands/terraform.go

- add auto-remove docker container
- fix flags to terraform commands
- fix gloabal flags
[![asciicast](https://asciinema.org/a/nnIEfhlBzuptobGiHe2VAnM1w.svg)](https://asciinema.org/a/nnIEfhlBzuptobGiHe2VAnM1w)

TOOLS-88 fix bugs

---

.github/workflows/build_on_push.yml
README.md

Fix Readme.md

---

go.mod
go.sum
internal/aws/utils/utils.go
internal/commands/config.go
internal/commands/env.go
internal/commands/tunnel.go

- add MFA request when MFA devices are installed
[![asciicast](https://asciinema.org/a/HWEWErWDI6sjFkLLX74wY9OX1.svg)](https://asciinema.org/a/HWEWErWDI6sjFkLLX74wY9OX1)

TOOLS-70 add request mfa

---

internal/commands/terraform.go

- add terraform output
[![asciicast](https://asciinema.org/a/QVMyUsSmsyD2UUUUMK2dZPEnV.svg)](https://asciinema.org/a/QVMyUsSmsyD2UUUUMK2dZPEnV)

TOOLS-86 add terraform output

---

go.mod
go.sum
internal/commands/base.go
internal/commands/ssh.go
pkg/ssmsession.go/ssmsession.go
pkg/term/interactive.go
pkg/term/interactive_windows.go
pkg/term/runner.go

- add SSH command for connection to ECS container
[![asciicast](https://asciinema.org/a/TSNBkOjf9J3v5tyCyXH8i5twC.svg)](https://asciinema.org/a/TSNBkOjf9J3v5tyCyXH8i5twC)

TOOLS-97 add ssh command

---

.github/workflows/build_on_push.yml
.github/workflows/build_on_release.yml
.github/workflows/create_dev_release.yml
.goreleaser_push.yml

- Added build and release of `dev` version on push

Add build on push (TOOLS-98)

---

.github/workflows/create_dev_release.yml

Add build on push2

---

go.mod
go.sum
internal/commands/base.go
internal/commands/init.go
internal/template/template.go

- add ize init command
[![asciicast](https://asciinema.org/a/SGBz3QpfePHschvH05sGRluQD.svg)](https://asciinema.org/a/SGBz3QpfePHschvH05sGRluQD)
[![asciicast](https://asciinema.org/a/GGY4ogLWxHB1Wsq6TFwq3d3I9.svg)](https://asciinema.org/a/GGY4ogLWxHB1Wsq6TFwq3d3I9)

TOOLS-99 add ize init command

---

.github/workflows/create_dev_release.yml

- Added `fury` cli commands to remove old version of dev packages in Gemfury

Add commands to remove old deb packages in Gemfury (TOOLS-98)

---

.github/workflows/create_dev_release.yml

Add commands to remove old deb packages in Gemfury

---

.github/workflows/create_dev_release.yml

- Minor fixes in github workflow

Minor fixes

---

.github/workflows/create_dev_release.yml

- Added ability to remove dev-version linux RPM packages from Gemfury repo before upload a new one

Add ability to remove rpm packages from Gemfury (CORE-225)

---

.github/workflows/create_dev_release.yml

- Uncomment   continue-on-error: true

Enable continue-on-error for packages list command

---

internal/commands/base.go
internal/commands/config.go
internal/commands/deploy.go
internal/commands/env.go
internal/commands/init.go
internal/commands/mfa.go
internal/commands/ssh.go
internal/commands/terraform.go
internal/commands/tunnel.go

- add short descriptions for all command and subcommand
- fix display global flags in help
https://asciinema.org/a/gojqDqCkzPQhycWwl8isbYQIk

TOOLS-115 add short desc and fix global args help

---

go.mod

- fix terraform commands
[![asciicast](https://asciinema.org/a/jLabDdyJbs38NM4FL3MnbClha.svg)](https://asciinema.org/a/jLabDdyJbs38NM4FL3MnbClha)

TOOLS-117 fix terraform commands

---

internal/commands/init.go
internal/config/config.go
internal/template/template.go

- add confirmation message when overwriting an existing file
[![asciicast](https://asciinema.org/a/KnUEuvlQWqkcAOc11jzQAvD3n.svg)](https://asciinema.org/a/KnUEuvlQWqkcAOc11jzQAvD3n)

TOOLS-114 add confirmation message overwriting

---

internal/commands/base.go

[![asciicast](https://asciinema.org/a/Iw3tYowGQH26JhcoauzjfExta.svg)]
(https://asciinema.org/a/Iw3tYowGQH26JhcoauzjfExta)

OPS-140 OPS-141

---

internal/commands/terraform.go

- fix terraform download bug
[![asciicast](https://asciinema.org/a/Fnnyl9gvmroefr2R1DEh1Ufq7.svg)](https://asciinema.org/a/Fnnyl9gvmroefr2R1DEh1Ufq7)
This is a temporary solution. The normal solution will be in TOOLS-112.

TOOLS-124 fix terraform download bug

---

README.md

- Added autocompletion manual to `Readme.md`

Add autocompletion manual to Readme (TOOLS-111)

---

internal/commands/deploy.go
internal/config/config.go

- add parsing terraform block as the main subblock
[![asciicast](https://asciinema.org/a/irNCeHmofeBXHljljVJ6dU1se.svg)](https://asciinema.org/a/irNCeHmofeBXHljljVJ6dU1se)

TOOLS-144 parse terraform block as main subblock

---

internal/commands/terraform.go

- fix cancel mid-run bug
[![asciicast](https://asciinema.org/a/Huohk01VKnR0Mr86BTgMS4Vft.svg)](https://asciinema.org/a/Huohk01VKnR0Mr86BTgMS4Vft)

TOOLS-142 fix cancel mid-run bug

---

go.mod
go.sum
internal/commands/base.go
internal/commands/deploy.go
internal/commands/env.go
internal/commands/helpers_test.go
internal/commands/ize.go
internal/commands/ssh.go
internal/commands/terraform.go
internal/commands/tunnel.go
internal/config/config.go

- rework logger
- terraform info logging improved
[![asciicast](https://asciinema.org/a/J7i6y9CdUvZOyJmwNhj9XbAsr.svg)](https://asciinema.org/a/J7i6y9CdUvZOyJmwNhj9XbAsr)

TOOLS-129 and TOOLS-112

---

internal/commands/mfa.go

- add check mfa devices
[![asciicast](https://asciinema.org/a/JtKzTtlY3WIO7kDdeRsqJtKws.svg)](https://asciinema.org/a/JtKzTtlY3WIO7kDdeRsqJtKws)

TOOLS-152 add check mfa devices

---

internal/commands/base.go
internal/commands/version.go

- add ize version command
[![asciicast](https://asciinema.org/a/8yM1Ho88ItgauVNl2jBzj9T9i.svg)](https://asciinema.org/a/8yM1Ho88ItgauVNl2jBzj9T9i)

TOOLS-145 add ize version command

---

internal/commands/base.go
internal/commands/secret.go

Changelog: 
- rename ize config to ize secret
- mark flags as required
[![asciicast](https://asciinema.org/a/ZNcG1avQsI7R9pKxsE3tncyYY.svg)](https://asciinema.org/a/ZNcG1avQsI7R9pKxsE3tncyYY)

TOOLS-150 TOOLS-151 ize secret

---

internal/commands/base.go
internal/commands/console.go
internal/commands/ssh.go

TOOLS-148 rework ssh desc

---

.gitignore
internal/commands/base.go
internal/commands/secret.go

- add force flag for ize secret set command
[![asciicast](https://asciinema.org/a/VvHLrFZL9BawcHZixLa6YFzzh.svg)](https://asciinema.org/a/VvHLrFZL9BawcHZixLa6YFzzh)

TOOLS-156 add force flag for ize set command

---

internal/commands/terraform.go

- rework ize terraform command
[![asciicast](https://asciinema.org/a/KSsAXwASYu1ca0K8lyDRfD8qL.svg)](https://asciinema.org/a/KSsAXwASYu1ca0K8lyDRfD8qL)

TOOLS-147 rework terraform command

---

internal/commands/deploy.go
internal/commands/terraform.go
internal/docker/terraform/terraform.go

- rework run terraform container
- add run terraform init and plan 
- add wait remove container
- add wait remove container
[![asciicast](https://asciinema.org/a/LOB0encdzUVOT0mtgRiJOsnDZ.svg)](https://asciinema.org/a/LOB0encdzUVOT0mtgRiJOsnDZ)

TOOLS-119 ize deploy infra

---

internal/commands/deploy.go
internal/commands/tunnel.go
internal/docker/terraform/terraform.go

- add upload terraform output to ssm
- fix getting terraform output via env
- add feature for create file for output
[![asciicast](https://asciinema.org/a/TQh13TMQNVdxyTy2Mp0ypop96.svg)](https://asciinema.org/a/TQh13TMQNVdxyTy2Mp0ypop96)

TOOLS-161 upload output to ssm

---

internal/commands/base.go
internal/commands/tunnel.go

- add flags for ssh keys
[![asciicast](https://asciinema.org/a/tM8D4dIuQjhmRmwHUBatxLNhC.svg)](https://asciinema.org/a/tM8D4dIuQjhmRmwHUBatxLNhC)
PS 
loading of parameters from the config file is not implemented

TOOLS-139 add flags for ssh keys

---

internal/commands/base.go
internal/commands/destroy.go

- add ize destroy infra command
[![asciicast](https://asciinema.org/a/deJiPDsb2BYTJ4brYbAMFQQvc.svg)](https://asciinema.org/a/deJiPDsb2BYTJ4brYbAMFQQvc)

TOOLS-106 add ize destroy infra command

---

internal/commands/base.go
internal/config/config.go

- add tag field
[![asciicast](https://asciinema.org/a/f0q9ILUAeM3bl3IE9jCrCHehh.svg)](https://asciinema.org/a/f0q9ILUAeM3bl3IE9jCrCHehh)

TOOLS-165 add tag field

---

internal/commands/deploy.go
internal/docker/ecsdeploy/ecs.go

- add deploy ecs service
[![asciicast](https://asciinema.org/a/9tqxdkW93MYT5H0bVQkPhI0et.svg)](https://asciinema.org/a/9tqxdkW93MYT5H0bVQkPhI0et)

TOOLS-164 add deploy ecs service

---

internal/commands/console/console.go
internal/commands/deploy/deploy.go
internal/commands/env/env.go
internal/config/config.go

- add getting docker registry while init
[![asciicast](https://asciinema.org/a/TCl6sLWx1OHFgZ1R6kORwWRR0.svg)](https://asciinema.org/a/TCl6sLWx1OHFgZ1R6kORwWRR0)

TOOLS-171 add getting docker registry while init

---

go.mod
go.sum
internal/commands/tunnel/tunnel.go
internal/commands/tunnel/tunnel_down.go
internal/commands/tunnel/tunnel_status.go
internal/commands/tunnel/tunnel_up.go

- add able to run in the background
[![asciicast](https://asciinema.org/a/SyJTrvxzDBRa8Zf3LOdsQtFcv.svg)](https://asciinema.org/a/SyJTrvxzDBRa8Zf3LOdsQtFcv)

TOOLS-130 add able to run in the background

---

internal/commands/deploy/deploy.go
pkg/templates/nornalizer.go

TOOLS-176 rework help to ize deploy

---

internal/commands/ize.go
internal/commands/terraform/terraform.go

- rework help to terraform command

TOOLS-174 rework help to terraform command

---

internal/commands/tunnel/tunnel.go
internal/commands/tunnel/tunnel_status.go
internal/commands/tunnel/tunnel_up.go

- add display current opened ports
[![asciicast](https://asciinema.org/a/OLEHiQCyMTDiXhIIad1zJqNaz.svg)](https://asciinema.org/a/OLEHiQCyMTDiXhIIad1zJqNaz)

TOOLS-107 add display current opened ports

---

internal/commands/tunnel/daemon.go
internal/commands/tunnel/tunnel.go
internal/commands/tunnel/tunnel_down.go
internal/commands/tunnel/tunnel_sshkey.go
internal/commands/tunnel/tunnel_status.go
internal/commands/tunnel/tunnel_up.go

- add alias to run ssh-key+up
[![asciicast](https://asciinema.org/a/3dPiayA27ndrtx9szuVH68SIN.svg)](https://asciinema.org/a/3dPiayA27ndrtx9szuVH68SIN)
upd:
[![asciicast](https://asciinema.org/a/AdfDZI7lxmyaQMDvcO6kBA5wQ.svg)](https://asciinema.org/a/AdfDZI7lxmyaQMDvcO6kBA5wQ)

TOOLS-160 add alias to run ssh-key+up

---

internal/commands/deploy/deploy.go

- add task definition arn, cluster flags
[![asciicast](https://asciinema.org/a/nzCZfYJiCQD9Jy6sgkRl8sMcz.svg)](https://asciinema.org/a/nzCZfYJiCQD9Jy6sgkRl8sMcz)
[![asciicast](https://asciinema.org/a/2jiKLDg5JqEY445MxeEkho3y8.svg)](https://asciinema.org/a/2jiKLDg5JqEY445MxeEkho3y8)

TOOLS-175 add task definition arn, cluster flags

---

.github/workflows/create_dev_release.yml
.goreleaser_push.yml

- Add prerelease option in goreleaser and release creation for dev builds

Add prerelease option in goreleaser and release creation for dev builds (TOOLS-181)

---

internal/commands/gendoc.go
internal/commands/ize.go

- set silence usage and silence errors
- remove version flag
[![asciicast](https://asciinema.org/a/gJ9JJfO6xNk6YOCtOzhxNazkn.svg)](https://asciinema.org/a/gJ9JJfO6xNk6YOCtOzhxNazkn)

TOOLS-201 TOOLS-188 when overwriting secrets in parameter store usage should not be shown

---

internal/commands/ize.go
internal/commands/terraform/terraform.go

- --version moved to a global --terraform-version
[![asciicast](https://asciinema.org/a/FeV1gePyy5WR5NBFchfkQSTIs.svg)](https://asciinema.org/a/FeV1gePyy5WR5NBFchfkQSTIs)

TOOLS-189 --version move to a global

---

internal/docker/terraform/terraform.go

- add signal handler for terraform container run
[![asciicast](https://asciinema.org/a/nd2AGea33yw2mUIqXhxz11Uka.svg)](https://asciinema.org/a/nd2AGea33yw2mUIqXhxz11Uka)

TOOLS-190 add signal handler

---

internal/commands/initialize/initialize.go
internal/generate/generate.go

- ize init creates a directory structure based on a template repo
[![asciicast](https://asciinema.org/a/CKzD6UXZ3GCMyr1gAdoP3nTyf.svg)](https://asciinema.org/a/CKzD6UXZ3GCMyr1gAdoP3nTyf)

TOOLS-203 ize init creates a directory structure based on a template repo

---

internal/commands/secrets/secrets.go
internal/commands/secrets/secrets_edit.go
internal/commands/secrets/secrets_push.go

- add ize secrets edit command
[![asciicast](https://asciinema.org/a/Y4EgXQwo8d5A5kAPIO26dOxmN.svg)](https://asciinema.org/a/Y4EgXQwo8d5A5kAPIO26dOxmN)

TOOLS-202 add ize secrets edit command

---

internal/commands/console/console.go
internal/commands/console/console_test.go

- add test for console command
- minor fixes
[![asciicast](https://asciinema.org/a/OXzbTRMI7DpKXJqA0rrELBGFq.svg)](https://asciinema.org/a/OXzbTRMI7DpKXJqA0rrELBGFq)

TOOLS-207 add tests for console command

---

internal/docker/terraform/terraform.go

- add display terraform output without log
[![asciicast](https://asciinema.org/a/OH7DoLFAnfV2FVVYBoiJSukn2.svg)](https://asciinema.org/a/OH7DoLFAnfV2FVVYBoiJSukn2)

TOOLS-210 add display terraform output without log

---

internal/commands/deploy/deploy.go
internal/commands/deploy/deploy_infra.go
internal/commands/destroy/destroy_infra.go

- override terraform version from global in deploy command
- override terraform version from global in deploy infra command
- override terraform version from global in destroy infra command
[![asciicast](https://asciinema.org/a/HY9g0zwLqEf3fPMoXBuSnkov9.svg)](https://asciinema.org/a/HY9g0zwLqEf3fPMoXBuSnkov9)

TOOLS-208 TOOLS-211 ize deploy infra honors default terraform version

---

cmd/main.go
internal/commands/ize.go
internal/commands/version.go

- add check latest version
[![asciicast](https://asciinema.org/a/eq6IH5Q6y8VpBYZXIsXIlQe0y.svg)](https://asciinema.org/a/eq6IH5Q6y8VpBYZXIsXIlQe0y)

TOOLS-205 add check latest version

---

.github/dependabot.yml

- Added settings for GitHub dependabot

Add dependabot (TOOLS-179)

---

.github/dependabot.yml

Add dependabot2

---

internal/commands/console/console.go
internal/commands/deploy/deploy.go
internal/commands/destroy/destroy_infra.go
internal/commands/terraform/terraform.go
internal/commands/tunnel/tunnel.go
internal/commands/tunnel/tunnel_up.go
internal/config/config.go
internal/config/helpers.go

- add dependency validation for only required tools
[![asciicast](https://asciinema.org/a/QtsD94IwfFUJMHmGmxIzlxz7H.svg)](https://asciinema.org/a/QtsD94IwfFUJMHmGmxIzlxz7H)

TOOLS-89 add dependency validation

---

internal/commands/deploy/deploy.go
internal/docker/ecsdeploy/ecs.go

- add a signal handler for ecs-deploy
[![asciicast](https://asciinema.org/a/PpoxX2ZvGwkwcYqldpglgPdTJ.svg)](https://asciinema.org/a/PpoxX2ZvGwkwcYqldpglgPdTJ)

TOOLS-215 add signal handler for ecs-deploy

---

internal/commands/tunnel/tunnel.go
internal/commands/tunnel/tunnel_down.go
internal/commands/tunnel/tunnel_sshkey.go
internal/commands/tunnel/tunnel_status.go
internal/commands/tunnel/tunnel_up.go
internal/config/config.go

- tunnel logging improved
[![asciicast](https://asciinema.org/a/9ItMfvWUCeT7fBnD0Vl21MHVJ.svg)](https://asciinema.org/a/9ItMfvWUCeT7fBnD0Vl21MHVJ)

TOOLS-146 TOOLS-197 TOOLS-196 tunnel logging improved

---

.github/dependabot.yml

- Changed count of open PR  to 30

Add - 30 PR option to dependabot

---

internal/commands/exec/exec.go
internal/commands/ize.go

- add exec command
[![asciicast](https://asciinema.org/a/adr5tkzMGFVFzrRFtirK44hFG.svg)](https://asciinema.org/a/adr5tkzMGFVFzrRFtirK44hFG)

TOOLS-191 add exec command

---

internal/docker/ecsdeploy/ecs.go

- add missing tag for push
[![asciicast](https://asciinema.org/a/oGL28LWoanKkt8liWIV09EZnB.svg)](https://asciinema.org/a/oGL28LWoanKkt8liWIV09EZnB)

TOOLS-170 add missing tag for push

---

go.mod
go.sum

- add require containerd v1.5.9
not required

TOOLS-187 add require containerd v1.5.9

---

go.mod
go.sum
internal/commands/deploy/dependencies.go
internal/commands/deploy/deploy.go
internal/docker/ecsdeploy/ecs.go

- add depends_on for service deploy
https://asciinema.org/a/VeRNQkonMlPss0R64SNpXtnBV

TOOLS-54 add depends_on for service deploy

---

internal/commands/tunnel/tunnel.go
internal/commands/tunnel/tunnel_up.go

- add forward-host and bastion id flags
[![asciicast](https://asciinema.org/a/BvDF09waFKo3HuTPuiG1XfLdX.svg)](https://asciinema.org/a/BvDF09waFKo3HuTPuiG1XfLdX)

TOOLS-136 add forward-host and bastion id flags

---

examples/embed.go
internal/commands/initialize/initialize.go
internal/generate/generate.go

- add init from internal examples
[![asciicast](https://asciinema.org/a/OhzvoZ1qfFMJaC2fGOzTFqsfo.svg)](https://asciinema.org/a/OhzvoZ1qfFMJaC2fGOzTFqsfo)

TOOLS-214 add init from internal examples

---

internal/config/config.go
internal/docker/ecsdeploy/ecs.go

- add display logs after a failed deployment
[![asciicast](https://asciinema.org/a/hGCQ7bvbsBvMWjArelsj1sbVx.svg)](https://asciinema.org/a/hGCQ7bvbsBvMWjArelsj1sbVx)

TOOLS-120 optionally print ecs logs after a failed deployment

---

go.mod
internal/commands/console/console.go
internal/commands/deploy/deploy.go
internal/commands/deploy/deploy_infra.go
internal/commands/exec/exec.go
internal/commands/mfa/mfa.go
internal/commands/secrets/secrets_push.go
internal/commands/secrets/secrets_rm.go
internal/commands/tunnel/tunnel.go
internal/commands/tunnel/tunnel_sshkey.go
internal/commands/tunnel/tunnel_up.go
internal/config/config.go
internal/docker/ecsdeploy/ecs.go

- fix duplicate AWS session request
- set AWS creds in tunnel commands
[![asciicast](https://asciinema.org/a/2Fr3FqEgP3rsjsinvrciF1aQp.svg)](https://asciinema.org/a/2Fr3FqEgP3rsjsinvrciF1aQp)

IZE-71 IZE-221 ize tunnel up with mfa inforced

---

internal/commands/ize.go

- add version flag
[![asciicast](https://asciinema.org/a/iUjzteca7Uomu5kC8k2Bhiijb.svg)](https://asciinema.org/a/iUjzteca7Uomu5kC8k2Bhiijb)

IZE-89 add version flag

---

internal/config/config.go

- add the ability to read any config file
[![asciicast](https://asciinema.org/a/LWkH0WAifaaY0hPu2ejU4Y4x6.svg)](https://asciinema.org/a/LWkH0WAifaaY0hPu2ejU4Y4x6)

IZE-220 add ability to read any config file

---

internal/commands/initialize/initialize.go

- add ability get list of internal examples
[![asciicast](https://asciinema.org/a/lNR3myeaQvlMbANqNGKEBX8cb.svg)](https://asciinema.org/a/lNR3myeaQvlMbANqNGKEBX8cb)

IZE-112 add ability get list of internal examples

---

internal/commands/terraform/terraform.go
internal/config/config.go

- set AWS creds in terraform container
[![asciicast](https://asciinema.org/a/ic5Dq4LEVmXd2qMTf5JVvfkzl.svg)](https://asciinema.org/a/ic5Dq4LEVmXd2qMTf5JVvfkzl)

IZE-70 set AWS creds in terraform container

---

internal/commands/env/env.go

- add TERRAFORM_STATE_BUCKET_NAME flag
[![asciicast](https://asciinema.org/a/5SmOYr2oeV4hre5ttYPZeJbYt.svg)](https://asciinema.org/a/5SmOYr2oeV4hre5ttYPZeJbYt)

IZE-104 add TERRAFORM_STATE_BUCKET_NAME flag

---

internal/commands/ize.go
internal/commands/logs/logs.go

- add logs command
[![asciicast](https://asciinema.org/a/K2dTsALQlxI1TimXVHPL3ED4f.svg)](https://asciinema.org/a/K2dTsALQlxI1TimXVHPL3ED4f)

IZE-111 add logs command

---

internal/commands/tunnel/tunnel.go
internal/commands/tunnel/tunnel_down.go
internal/commands/tunnel/tunnel_status.go
internal/commands/tunnel/tunnel_up.go
internal/config/config.go

- add an env dir assignment
- set env dir as the executable dir
[![asciicast](https://asciinema.org/a/EHgC6J70znzQCuyWZuPBv0QnF.svg)](https://asciinema.org/a/EHgC6J70znzQCuyWZuPBv0QnF)
[![asciicast](https://asciinema.org/a/yerN2TYgviz0h7Ww1fMncz5IS.svg)](https://asciinema.org/a/yerN2TYgviz0h7Ww1fMncz5IS)

IZE-222 directory structure for global tunnel configuration

---

internal/commands/console/console.go
internal/commands/deploy/deploy.go
internal/commands/deploy/deploy_infra.go
internal/commands/destroy/destroy_infra.go
internal/commands/env/env.go
internal/commands/exec/exec.go
internal/commands/initialize/initialize.go
internal/commands/logs/logs.go
internal/commands/mfa/mfa.go
internal/commands/secrets/secrets_edit.go
internal/commands/secrets/secrets_push.go
internal/commands/secrets/secrets_rm.go
internal/commands/terraform/terraform.go
internal/commands/tunnel/tunnel.go
internal/commands/tunnel/tunnel_down.go
internal/commands/tunnel/tunnel_sshkey.go
internal/commands/tunnel/tunnel_status.go
internal/commands/tunnel/tunnel_up.go
internal/config/config.go

- fix new line in errors
- fix typos mfa command
- fix sending mfa creds in container
[![asciicast](https://asciinema.org/a/Jz88q8CVMO8nRWOodmYfl4ev3.svg)](https://asciinema.org/a/Jz88q8CVMO8nRWOodmYfl4ev3)

IZE-231 IZE-232 IZE-233 fix bugs

---

README.md

- Added installation instructions for Ubuntu to the main manual.

Manual updated (IZE_86)

---

internal/config/config.go

- move warning about config file to log
[![asciicast](https://asciinema.org/a/K8ckGNLx3xHvPt80EIeYuAUJa.svg)](https://asciinema.org/a/K8ckGNLx3xHvPt80EIeYuAUJa)

IZE-229 move warning about config file to log

---

internal/config/config.go

- .ize dir is accepted same way as .infra
[![asciicast](https://asciinema.org/a/OJWq790DOk98VmyHnI5FWEclr.svg)](https://asciinema.org/a/OJWq790DOk98VmyHnI5FWEclr)

IZE-151 .ize dir is accepted same way as .infra

---

internal/commands/deploy/deploy.go
internal/services/alias.go
internal/services/ecs.go
internal/services/serverless.go
internal/services/service.go

- add alias type
[![asciicast](https://asciinema.org/a/GRDdS8CCZX5uOAH5hIsKWLEFM.svg)](https://asciinema.org/a/GRDdS8CCZX5uOAH5hIsKWLEFM)

IZE-227 alias service type

---

go.mod
internal/commands/deploy/deploy.go
internal/commands/destroy/destroy.go
internal/commands/destroy/destroy_infra.go
internal/services/alias.go
internal/services/dependencies.go
internal/services/ecs.go
internal/services/interface.go
internal/services/serverless.go
internal/services/service.go

- add destroy methods for all type apps
- add destroy all and destroy app commands
[![asciicast](https://asciinema.org/a/x76UQfaa15tQQu0Pa78j79AUN.svg)](https://asciinema.org/a/x76UQfaa15tQQu0Pa78j79AUN)

IZE-237 IZE-238 add destroy commands

---

internal/config/config.go

- add printing out which file parsing issues

IZE-215 add printing out which file has parsing issues

---

examples/simple-monorepo/.infra/env/testnut/ize.toml
internal/apps/alias.go
internal/apps/dependencies.go
internal/apps/ecs.go
internal/apps/interface.go
internal/apps/serverless.go
internal/apps/service.go
internal/commands/console/console.go
internal/commands/deploy/deploy.go
internal/commands/destroy/destroy.go
internal/commands/exec/exec.go
internal/commands/logs/logs.go

- rename service to app
[![asciicast](https://asciinema.org/a/ZMPRnWldJW0qXr3fMxsdl2qvm.svg)](https://asciinema.org/a/ZMPRnWldJW0qXr3fMxsdl2qvm)

IZE-228 rename service to app

---

internal/commands/tunnel/tunnel.go
internal/commands/tunnel/tunnel_up.go

- add reading tunnel config from config file
[![asciicast](https://asciinema.org/a/wmUW4z3E5lABEPi5zubSOxWUC.svg)](https://asciinema.org/a/wmUW4z3E5lABEPi5zubSOxWUC)

IZE-150 add reading tunnel config from config file

---

.goreleaser.yml
.goreleaser_push.yml

- Added conflict packages to goreleaser

Add conflict packages (IZE-214)

---

internal/apps/ecs.go

-- add native ECS deploy
no required

IZE-251 add native ECS deploy

---

internal/commands/tunnel/tunnel.go
internal/commands/tunnel/tunnel_status.go
internal/commands/tunnel/tunnel_up.go

- fix tunnel up bugs
[![asciicast](https://asciinema.org/a/Hm4xXjahdatEqndClWxP9QcQb.svg)](https://asciinema.org/a/Hm4xXjahdatEqndClWxP9QcQb)

IZE-263 IZE-264 fix tunnel up bugs

---

internal/apps/ecs.go

- add ecs healthcheck
[![asciicast](https://asciinema.org/a/1wOnNSJtJOo8Vc2GFT25HjDFW.svg)](https://asciinema.org/a/1wOnNSJtJOo8Vc2GFT25HjDFW)

IZE-252 add ecs healthcheck

---

internal/terraform/docker.go

- add user input handler for ize terraform
[![asciicast](https://asciinema.org/a/tefmRI9LsavBVE5G5KusNHozs.svg)](https://asciinema.org/a/tefmRI9LsavBVE5G5KusNHozs)

IZE-287 add user input handler for ize terraform

---

internal/apps/ecs.go

- add rollback for ECS deploy 
[![asciicast](https://asciinema.org/a/tG6QRZyU3KaT1Q0cpZLbFie3y.svg)](https://asciinema.org/a/tG6QRZyU3KaT1Q0cpZLbFie3y)
[![asciicast](https://asciinema.org/a/A0dDBr0SYcHwBUsMtoJwkL0nD.svg)](https://asciinema.org/a/A0dDBr0SYcHwBUsMtoJwkL0nD)

IZE-253 add rollback for ECS deploy

---

.github/workflows/smoke_tests.yml

More fixes to smoke tests

---

internal/terraform/local.go

- add working dir for terraform run
[![asciicast](https://asciinema.org/a/HxoXTnTV9FmUSfXvyzjLRfsZ5.svg)](https://asciinema.org/a/HxoXTnTV9FmUSfXvyzjLRfsZ5)

IZE-288 add working dir for terraform run

---

cmd/main.go
internal/commands/console/console.go
internal/commands/console/console_test.go
internal/commands/deploy/deploy.go
internal/commands/deploy/deploy_infra.go
internal/commands/destroy/destroy.go
internal/commands/destroy/destroy_infra.go
internal/commands/env/env.go
internal/commands/exec/exec.go
internal/commands/gendoc.go
internal/commands/ize.go
internal/commands/logs/logs.go
internal/commands/mfa/mfa.go
internal/commands/secrets/secrets.go
internal/commands/secrets/secrets_edit.go
internal/commands/secrets/secrets_push.go
internal/commands/secrets/secrets_rm.go
internal/commands/terraform/terraform.go
internal/commands/tunnel/tunnel.go
internal/commands/tunnel/tunnel_down.go
internal/commands/tunnel/tunnel_sshkey.go
internal/commands/tunnel/tunnel_status.go
internal/commands/tunnel/tunnel_up.go
internal/config/config.go
internal/config/helpers.go
pkg/terminal/basic.go

- add "plain-text" flag
[![asciicast](https://asciinema.org/a/qrRMMIwTOMkpsgp8EzHGhlDQs.svg)](https://asciinema.org/a/qrRMMIwTOMkpsgp8EzHGhlDQs)

IZE-262 plain text commands available to all commands

---

internal/commands/tunnel/tunnel_up.go

- fix ui init in tunnel up
[![asciicast](https://asciinema.org/a/ECW47gcqzyQZBhNhP6kWHZEdw.svg)](https://asciinema.org/a/ECW47gcqzyQZBhNhP6kWHZEdw)

IZE-302 fix ui init

---

.github/workflows/build_on_release.yml

- Added creat JIRA release github action

Add JIRA release (IZE-294)

---

internal/apps/alias.go
internal/apps/ecs.go
internal/apps/serverless.go
internal/commands/console/console.go
internal/commands/deploy/deploy.go
internal/commands/destroy/destroy.go
internal/commands/destroy/destroy_infra.go
internal/commands/exec/exec.go
internal/commands/ize.go
internal/commands/secrets/secrets_push.go
internal/commands/secrets/secrets_rm.go
internal/commands/tunnel/tunnel.go
internal/commands/tunnel/tunnel_down.go
internal/commands/tunnel/tunnel_sshkey.go
internal/commands/tunnel/tunnel_status.go
internal/commands/tunnel/tunnel_up.go
internal/config/config.go
internal/terraform/docker.go
internal/terraform/local.go

- make text with a capital letter in output
- change ui package to pterm
[![asciicast](https://asciinema.org/a/9lZvtmwyBRX7uVpnZI4DceH7k.svg)](https://asciinema.org/a/9lZvtmwyBRX7uVpnZI4DceH7k)

IZE-271 text that starts from a new line in a terminal output is capitalized

---

internal/commands/console/console.go
internal/commands/exec/exec.go
internal/commands/ize.go

- add task id flag
[![asciicast](https://asciinema.org/a/WDrD5NW7wFIkRWhRvksk8NkWT.svg)](https://asciinema.org/a/WDrD5NW7wFIkRWhRvksk8NkWT)

IZE-297 add task id flag

---

.github/workflows/build_on_release.yml
DOCS.md
README.md
internal/commands/gen/completion.go
internal/commands/gen/doc.go
internal/commands/gen/env.go
internal/commands/gen/gen.go
internal/commands/gen/mfa.go
internal/commands/ize.go

- add gen sub command
[![asciicast](https://asciinema.org/a/HFGhRNuONBvCh94U4wuFsVtqO.svg)](https://asciinema.org/a/HFGhRNuONBvCh94U4wuFsVtqO)

IZE-269 add gen sub command

---

internal/commands/ize.go

- return exit code 1 on error
[![asciicast](https://asciinema.org/a/YkTSetcLFny7EiyKu0Go2dgm6.svg)](https://asciinema.org/a/YkTSetcLFny7EiyKu0Go2dgm6)

IZE-322 return exit code 1 on error

---

internal/commands/configure/configure.go
internal/commands/console/console.go
internal/commands/deploy/deploy.go
internal/commands/deploy/deploy_infra.go
internal/commands/destroy/destroy.go
internal/commands/destroy/destroy_infra.go
internal/commands/exec/exec.go
internal/commands/gen/doc.go
internal/commands/gen/env.go
internal/commands/gen/gen.go
internal/commands/gen/mfa.go
internal/commands/initialize/initialize.go
internal/commands/logs/logs.go
internal/commands/secrets/secrets.go
internal/commands/secrets/secrets_edit.go
internal/commands/secrets/secrets_push.go
internal/commands/secrets/secrets_rm.go
internal/commands/status/status.go
internal/commands/terraform/terraform.go
internal/commands/tunnel/tunnel.go
internal/commands/tunnel/tunnel_down.go
internal/commands/tunnel/tunnel_sshkey.go
internal/commands/tunnel/tunnel_status.go
internal/commands/tunnel/tunnel_up.go
internal/commands/version.go

IZE-274, IZE-276, IZE-270, IZE-280, IZE-281

---

internal/commands/deploy/deploy.go
internal/commands/deploy/deploy_infra.go

- use out for terraform plan
[![asciicast](https://asciinema.org/a/2VXJOQojjD7QkbEdYN25axIT3.svg)](https://asciinema.org/a/2VXJOQojjD7QkbEdYN25axIT3)

IZE-327 use out for terraform plan

---

internal/commands/status/status.go

IZE-325 handle NoSuchEntity error

---

internal/commands/gen/env.go
internal/template/template.go

[![asciicast](https://asciinema.org/a/rsq30eeWkk9asWtYJufCDypZq.svg)](https://asciinema.org/a/rsq30eeWkk9asWtYJufCDypZq)

Add root_domain_name optional variable value to terraform

---

internal/commands/deploy/deploy.go
internal/commands/deploy/deploy_infra.go
test-e2e/ecs_apps_test.go

- fix: add multiple iterations of secret checking
- add terraform files generation
- refactoring

IZE-317 IZE-259 generation tf files and refactoring

---

.github/workflows/smoke_tests.yml

IZE-303-run-end-to-end-integration-tests-during-pr-via-ci-cd

---

.github/workflows/create_dev_release.yml

Add permission to github job

---

.github/workflows/create_dev_release.yml

add permission to github job2

---

.github/dependabot.yml
.github/workflows/create_dev_release.yml

fix dev-release

---

internal/apps/alias.go
internal/apps/dependencies.go
internal/apps/ecs.go
internal/apps/interface.go
internal/apps/serverless.go
internal/commands/build/build.go
internal/commands/deploy/deploy.go
internal/commands/down/down.go
internal/commands/down/down_infra.go
internal/commands/ize.go
internal/commands/push/push.go
internal/commands/up/up.go
internal/commands/up/up_infra.go
internal/docker/registry.go
test-e2e/ecs_apps_test.go

- add build command
- add push command
- move old deploy command to up command
- add registry package
- fix launch apps with dependencies
- add push and build interfaces for apps
- some refactoring
[![asciicast](https://asciinema.org/a/GZ6I6iivf0nzlKngT5fakoxb3.svg)](https://asciinema.org/a/GZ6I6iivf0nzlKngT5fakoxb3)

IZE-309 build, push and deploy commands

---

.goreleaser_push.yml

- Added windows x64 build to develop release

add windows x64 build

---

internal/apps/ecs.go

- fix image downloading if runtime is native

IZE-356 fix image downloading if runtime is native

---

internal/apps/ecs.go
internal/apps/serverless.go
internal/config/config.go

- add projects path variable
[![asciicast](https://asciinema.org/a/E3eGwoYffTtuWgRLYP08qIWKf.svg)](https://asciinema.org/a/E3eGwoYffTtuWgRLYP08qIWKf)
[![asciicast](https://asciinema.org/a/8itxfS4Lieer77dPvCS7OOEm5.svg)](https://asciinema.org/a/8itxfS4Lieer77dPvCS7OOEm5)

IZE-351 add projects path variable

---

internal/commands/gen/env.go

- override terraform state bucket region
[![asciicast](https://asciinema.org/a/C2ZVQOzvUh539y741tnOZjfZ5.svg)](https://asciinema.org/a/C2ZVQOzvUh539y741tnOZjfZ5)

IZE-329 override terraform state bucket region

---

internal/commands/secrets/secrets.go
internal/commands/secrets/secrets_pull.go

- add new command `ize secrets pull `
[![asciicast](https://asciinema.org/a/gPABCssdXvetPkSHhZzEcKrvx.svg)](https://asciinema.org/a/gPABCssdXvetPkSHhZzEcKrvx)

IZE-285 add secrets pull command

---

internal/apps/ecs/ecs.go

- fix build docker image
[![asciicast](https://asciinema.org/a/qy5d9aJjZgyL4Be94VoRsVCNb.svg)](https://asciinema.org/a/qy5d9aJjZgyL4Be94VoRsVCNb)

IZE-368 fix build docker image

---

internal/commands/gen/doc.go

- fix ize gen doc command
[![asciicast](https://asciinema.org/a/2qI8swefBCPHHUZIKQZ6SwXl2.svg)](https://asciinema.org/a/2qI8swefBCPHHUZIKQZ6SwXl2)

fix ize gen doc command

---

internal/commands/up/up.go
internal/commands/up/up_infra.go

- add a flag to skip terraform file generation
[![asciicast](https://asciinema.org/a/sokg0vw0zUE5YEYdNLZ1LHvPO.svg)](https://asciinema.org/a/sokg0vw0zUE5YEYdNLZ1LHvPO)

IZE-360 add a flag to skip terraform file generation

---

internal/commands/terraform/terraform.go
internal/commands/up/up.go
internal/commands/up/up_infra.go

- implement version under infra.terraform
[![asciicast](https://asciinema.org/a/3dXtiSBkUeKt6iYxbeECgoQGo.svg)](https://asciinema.org/a/3dXtiSBkUeKt6iYxbeECgoQGo)

IZE-336 implement version under infra.terraform

---

internal/commands/gen/aws_profile.go
internal/commands/gen/gen.go

- add ize gen aws_profile command
[![asciicast](https://asciinema.org/a/qgTAmotdAQ6lZ5sixng0v8O7E.svg)](https://asciinema.org/a/qgTAmotdAQ6lZ5sixng0v8O7E)

IZE-308 add ize gen aws_profile command

---

internal/apps/alias.go
internal/apps/ecs/docker.go
internal/apps/ecs/ecs.go
internal/apps/ecs/native.go
internal/apps/interface.go
internal/apps/serverless.go
internal/commands/deploy/deploy.go

- add task definition revision flag
- add logic for ECS redeploy
[![asciicast](https://asciinema.org/a/tUfVDzIJp2SbO9qGN9OPeIT1v.svg)](https://asciinema.org/a/tUfVDzIJp2SbO9qGN9OPeIT1v)
[![asciicast](https://asciinema.org/a/eir3Lw17wqOgE9xZqNwshyZLj.svg)](https://asciinema.org/a/eir3Lw17wqOgE9xZqNwshyZLj)

add td revision flag and logic to ECS redeploy

---

.github/workflows/smoke_tests.yml

- Added 'windows-latest' to the tests matrix

IZE-357-tests-ci-cd-windows-platform-on-github-actions

---

internal/commands/gen/gen.go
internal/commands/gen/tfenv.go
internal/commands/up/up.go

- rename ize gen env -> ize gen tfenv
[![asciicast](https://asciinema.org/a/OIYYuD6ErrGRvAoxNkRw7O6Eu.svg)](https://asciinema.org/a/OIYYuD6ErrGRvAoxNkRw7O6Eu)

IZE-371 rename ize gen env -> ize gen tfenv

---

.github/workflows/build_on_push.yml
.github/workflows/create_dev_release.yml
.goreleaser.yml
.goreleaser_push.yml

Add Date and user to release version

---

.github/workflows/build_on_push.yml
.github/workflows/build_on_release.yml
.goreleaser.yml
.goreleaser_push.yml

- Added short sha for release version

Short sha for release version and date and user for development version

---

internal/apps/ecs/ecs.go
internal/apps/ecs/native.go
internal/commands/deploy/deploy.go
internal/commands/down/down.go
internal/commands/up/up.go
pkg/templates/nornalizer.go

- add an unsafe parameter to speed up deployment
[![asciicast](https://asciinema.org/a/qkkZMMsnzJit249uv4qqhFDXc.svg)](https://asciinema.org/a/qkkZMMsnzJit249uv4qqhFDXc)

IZE-146 add an unsafe parameter to speed up deployment

---

go.mod
go.sum
internal/commands/ize.go
internal/commands/validate/validate.go
internal/config/app.go
internal/config/config.go
internal/config/infra.go
internal/config/project.go
internal/schema/ize-spec.json
internal/schema/schema.go

- add json schema for `ize` configuration
- describe the configuration structure
- add schema package to validate the configuration
- add command to test the schema validation
[![asciicast](https://asciinema.org/a/k7FDkytEak9ydddfr9bqkjowO.svg)](https://asciinema.org/a/k7FDkytEak9ydddfr9bqkjowO)

IZE-378 ize toml schema

---

internal/commands/down/down_infra.go
internal/config/config.go

[![asciicast](https://asciinema.org/a/eWq7tPYVOlj5bj1R7OFzqCpin.svg)](https://asciinema.org/a/eWq7tPYVOlj5bj1R7OFzqCpin)

Fixes key with hyphen (we've reversed the replacement logic

---

.goreleaser.yml
.goreleaser_push.yml
Makefile
internal/commands/initialize/initialize.go

- set first arg as output folder
- add wizard init
[![asciicast](https://asciinema.org/a/RRueLW5ZhKiOJosd73Uye4BYI.svg)](https://asciinema.org/a/RRueLW5ZhKiOJosd73Uye4BYI)
[![asciicast](https://asciinema.org/a/tOg0oZ1LjS9yHcZS01uDTm59O.svg)](https://asciinema.org/a/tOg0oZ1LjS9yHcZS01uDTm59O)

IZE-387 IZE-386 init

---

internal/commands/console/console.go

[![asciicast](https://asciinema.org/a/CG2XNLZ9SeNEcw80selTTBse1.svg)](https://asciinema.org/a/CG2XNLZ9SeNEcw80selTTBse1)

Add custom-prompt parameter

---

internal/commands/validate/validate.go
internal/config/config.go
internal/schema/ize-spec.json

- adding converting old schemas apps and infra
[![asciicast](https://asciinema.org/a/rdezIc6vobCq8Qvb76AVxojTW.svg)](https://asciinema.org/a/rdezIc6vobCq8Qvb76AVxojTW)

IZE-388 adding converting old schemas apps and infra

---

internal/commands/down/down.go
internal/commands/down/down_infra.go
internal/commands/gen/tfenv.go
internal/commands/up/up.go

- refactoring `tfenv` command
- add `tfenv` to `down` commands
[![asciicast](https://asciinema.org/a/ZEUtIcH8dOeVO6EqyodfZt8v8.svg)](https://asciinema.org/a/ZEUtIcH8dOeVO6EqyodfZt8v8)

IZE-398 ize destroy infra generates tfenv

---

internal/commands/ize.go
internal/config/helpers.go
internal/version/version.go

- add showing commands for upgrade `ize`
[![asciicast](https://asciinema.org/a/Zk4btNSFgrllLVM3UYX203YPR.svg)](https://asciinema.org/a/Zk4btNSFgrllLVM3UYX203YPR)

IZE-364 add showing commands for upgrade `ize`

---

internal/commands/initialize/initialize.go

- improve table view 
```
ize init --list
Name                    | Version        
bastion-tunnel-monorepo | 8354c37+CHANGES
ecs-apps-monorepo       | 8354c37+CHANGES
```

IZE-343 improve table view

---

README.md
internal/commands/initialize/initialize.go

[![asciicast](https://asciinema.org/a/bRuD0bs9mYleREgl2ABZrkFIB.svg)](https://asciinema.org/a/bRuD0bs9mYleREgl2ABZrkFIB)

Updated README, added minor ux improvements for `ize init`

---

.github/workflows/build_dev_release.yml
.github/workflows/build_on_release.yml
.github/workflows/create_dev_release.yml
.goreleaser.yml
.goreleaser_push.yml

- Added concurrency to github actions

Add concurrency to github actions

---

internal/config/app.go
internal/config/config.go
internal/manager/ecs/ecs.go
internal/schema/ize-spec.json

- add docker_registry parameter for ECS apps
[![asciicast](https://asciinema.org/a/bJQlXNsLGUh7dmmVzPXf4lG8v.svg)](https://asciinema.org/a/bJQlXNsLGUh7dmmVzPXf4lG8v)

IZE-413 docker registry is configurable on the app level

---

internal/manager/ecs/ecs.go

- add `APP_PATH` to docker build args
[![asciicast](https://asciinema.org/a/Y36YmZbXGV8tBYU9fOONB6vAr.svg)](https://asciinema.org/a/Y36YmZbXGV8tBYU9fOONB6vAr)

IZE-412 add `APP_PATH` to docker build args

---

internal/commands/gen/ci.go

- add generation GitHub Actions from a template
[![asciicast](https://asciinema.org/a/S6u0C6PYRRMLN363hBQ0JFHCc.svg)](https://asciinema.org/a/S6u0C6PYRRMLN363hBQ0JFHCc)

IZE-149 add generation GitHub Actions from a template

---

README.md

Build & Publish dev Release status badge

---

internal/commands/deploy/deploy.go
internal/commands/down/down.go
internal/commands/terraform/terraform.go
internal/commands/up/up.go
internal/commands/up/up_infra.go
internal/config/config.go

- add ize structured repo detection
[![asciicast](https://asciinema.org/a/zYWfLnekRLTIwhtFTyfVGD6cQ.svg)](https://asciinema.org/a/zYWfLnekRLTIwhtFTyfVGD6cQ)

IZE-334 add ize structured repo detection

---

.github/workflows/build_on_release.yml

Add codecoverage test

---

.github/workflows/build_on_release.yml
README.md

- Added Codecov badge
- Added condition not to run Codecov test on push

Add Codecov badge

---

internal/commands/build/build.go
internal/commands/console/console.go
internal/commands/deploy/deploy.go
internal/commands/down/down.go
internal/commands/exec/exec.go
internal/commands/logs/logs.go
internal/commands/push/push.go
internal/commands/secrets/secrets_edit.go
internal/commands/secrets/secrets_pull.go
internal/commands/secrets/secrets_push.go
internal/commands/secrets/secrets_rm.go
internal/commands/up/up.go
internal/config/helpers.go

- add autocomplete app names
[![asciicast](https://asciinema.org/a/C8ixrVqztHO5hL5uHDFICJv3Z.svg)](https://asciinema.org/a/C8ixrVqztHO5hL5uHDFICJv3Z)

IZE-402 add autocomplete app names

---

internal/commands/down/down.go
internal/commands/ize.go
internal/commands/tunnel/tunnel_sshkey.go
internal/commands/up/up.go
internal/config/config.go
internal/schema/ize-spec.json

- fix global flags
- fix unrendered format string to `tunnel ssh-key`
- fix deploy apps using `up` and `down` commands
[![asciicast](https://asciinema.org/a/t3yZyaBx55ZVhjXQpOGBSsseT.svg)](https://asciinema.org/a/t3yZyaBx55ZVhjXQpOGBSsseT)
[![asciicast](https://asciinema.org/a/s9MSn24Xar2XuRi4yVsk0SieK.svg)](https://asciinema.org/a/s9MSn24Xar2XuRi4yVsk0SieK)

IZE-430 IZE-436 IZE-433 fix bugs

---

internal/commands/gen/tfenv.go
internal/template/template.go

- add default tags generation in `backend.tf`
[![asciicast](https://asciinema.org/a/iNtqNQKiygUGS1lwWWThcCPfw.svg)](https://asciinema.org/a/iNtqNQKiygUGS1lwWWThcCPfw)

IZE-393 add default tags generation in `backend.tf`

---

.goreleaser.yml
.goreleaser_push.yml
DOCS.md

IZE-358 Add scoop to goreleaser

---

internal/config/app.go
internal/manager/ecs/ecs.go
internal/schema/ize-spec.json

- add `skip_deploy` parameter for ecs apps
[![asciicast](https://asciinema.org/a/3RKoduP0uQWXUTZhSJxFdSev2.svg)](https://asciinema.org/a/3RKoduP0uQWXUTZhSJxFdSev2)

IZE-411 add `skip_deploy` parameter for ecs apps

---

examples/ecs-apps-monorepo/apps/pecan/package.json
examples/ecs-apps-monorepo/apps/pecan/serverless.yml

- upgrade pecan to serverless v2
[![asciicast](https://asciinema.org/a/2oxQl2tps0SbB3YzBpVKOfzBJ.svg)](https://asciinema.org/a/2oxQl2tps0SbB3YzBpVKOfzBJ)

IZE-462 upgrade pecan to serverless v2

---

internal/commands/gen/ci.go
internal/terraform/local.go

- add an example for ize gen ci
[![asciicast](https://asciinema.org/a/geO5citmw3jwVGYQZ2vWuZRcT.svg)](https://asciinema.org/a/geO5citmw3jwVGYQZ2vWuZRcT)

IZE-420 ize gen ci documentation created

---

internal/commands/initialize/initialize.go

- fix generate terraform block in ize.toml
[![asciicast](https://asciinema.org/a/EwHbhG0SsLDJhRC84vJQtWHBs.svg)](https://asciinema.org/a/EwHbhG0SsLDJhRC84vJQtWHBs)

IZE-467 fix generate terraform block in ize.toml

---

internal/manager/ecs/native.go

- add stopped reason in deploy log
[![asciicast](https://asciinema.org/a/EcTaulEAhoxkq90RpLb4pdSij.svg)](https://asciinema.org/a/EcTaulEAhoxkq90RpLb4pdSij)

IZE-440 add stopped reason in deploy log

---

.github/workflows/terraform-test.yml

- add ize terraform download test

Terraform test

---

internal/commands/down/down.go
internal/commands/gen/tfenv.go
internal/commands/up/up.go
internal/template/template.go

- add checking md5 hash for backend.tf
- fix reading `state_bucket_name` from `terraform.infra`
[![asciicast](https://asciinema.org/a/U9wNq64tZM5mdhyVmaBTtgLUr.svg)](https://asciinema.org/a/U9wNq64tZM5mdhyVmaBTtgLUr)
[![asciicast](https://asciinema.org/a/dUDWjOuyJXx4bpRJU5F4uhwMQ.svg)](https://asciinema.org/a/dUDWjOuyJXx4bpRJU5F4uhwMQ)

IZE-486 IZE-495 backend tf is not updated if it exists but different contents

---

internal/schema/ize-spec.json

- remove type field from plain_text parameter 
- change type of timeout parameter from string to int
[![asciicast](https://asciinema.org/a/7DtsvQzHQNWPIyXQar4LF0Kq4.svg)](https://asciinema.org/a/7DtsvQzHQNWPIyXQar4LF0Kq4)

IZE-489 IZE-484 fixes

---

internal/manager/serverless/native.go

- add nvm run before using npm command
- remove error texts in sls deploy functions
[![asciicast](https://asciinema.org/a/eKoRYR2k9hvZa3A8bvRiL1v1n.svg)](https://asciinema.org/a/eKoRYR2k9hvZa3A8bvRiL1v1n)

IZE-482 IZE-481 add nvm run before using npm command

---

internal/config/app.go
internal/manager/ecs/docker.go
internal/manager/ecs/ecs.go
internal/manager/serverless/docker.go
internal/manager/serverless/native.go
internal/manager/serverless/serverless.go
internal/schema/ize-spec.json

- add `aws_region` and `aws_profile` options for apps config
[![asciicast](https://asciinema.org/a/PuaCLZwJytsr3ICRTqkFHN5sT.svg)](https://asciinema.org/a/PuaCLZwJytsr3ICRTqkFHN5sT)
[![asciicast](https://asciinema.org/a/Q5cH55N60GDUtUpieUTudH4D7.svg)](https://asciinema.org/a/Q5cH55N60GDUtUpieUTudH4D7)

add `aws_region` and `aws_profile` options for apps config

---

internal/commands/ize.go

- fix bind persistent flags
[![asciicast](https://asciinema.org/a/1C3Z6MphaNIczerQxhDNLfejk.svg)](https://asciinema.org/a/1C3Z6MphaNIczerQxhDNLfejk)

fix bind persistent flags

---

internal/aws/utils/utils.go
internal/manager/ecs/ecs.go

- handle SharedCredsLoad error
[![asciicast](https://asciinema.org/a/ZmlCMJMcyLIKMUysshBdrRUrL.svg)](https://asciinema.org/a/ZmlCMJMcyLIKMUysshBdrRUrL)

handle SharedCredsLoad error

---

internal/config/config.go

- add deprecation message for docker runtime
[![asciicast](https://asciinema.org/a/VTu8fCqSfcrNIxYcE1YiJ7K2J.svg)](https://asciinema.org/a/VTu8fCqSfcrNIxYcE1YiJ7K2J)

add deprecation message for docker runtime

---

internal/manager/ecs/native.go

- fix nil pointer panic
- add ECS deployment using the latest task definition
[![asciicast](https://asciinema.org/a/F4XwpWq9Gi3iqJV5d0l90CIJW.svg)](https://asciinema.org/a/F4XwpWq9Gi3iqJV5d0l90CIJW)

IZE-465 IZE-512 ize deploy ecs uses latest task definition in native

---

internal/commands/deploy/deploy.go
internal/commands/down/down.go
internal/commands/down/down_infra.go
internal/commands/up/up.go
internal/commands/up/up_infra.go

- change order of calling requirements checking and getting config
[![asciicast](https://asciinema.org/a/df3JsmAobcxksDmWs092REDd1.svg)](https://asciinema.org/a/df3JsmAobcxksDmWs092REDd1)

change order of calling requirements checking and getting config

---

.github/workflows/run.e2e-tests.yml
internal/commands/ize.go
internal/config/helpers.go
internal/version/version.go
test-e2e/ecs_apps_test.go
test-e2e/terraform_test.go

- Improved e2e GHA workflow (added temp ssh keys, rename jobs, rearrange vars)
- Renamed Tests
- Split up infra / up squibby-goblin tests
- Detect EOF error - issue with ssm agent
- Show more debug when secret check happens
- Added ize secret rm afterwards
- Fix typo
- Test multiple Terraform versions
- Use downgrade/upgrade language when suggested to change version
https://github.com/hazelops/ize/actions/runs/2920891740

WIP: IZE-523 tests are not working properly + Minor changes

---

.github/workflows/release-prod.build-and-publish.yml
.github/workflows/run.e2e-tests.yml
.github/workflows/run.unit-tests.yml
README.md

- Update README to link to a proper build
- Run unit tests on PRs to main
- Run E2E on PRs to main

IZE-530: Tests Improved

---

internal/commands/gen/tfenv.go

- new default state bucket name
[![asciicast](https://asciinema.org/a/Z3oFDHvyYFrbAp3nC9U1vp3SZ.svg)](https://asciinema.org/a/Z3oFDHvyYFrbAp3nC9U1vp3SZ)

IZE-479 New default state bucket name

---

go.mod
internal/commands/console/console.go
internal/commands/tunnel/tunnel_up.go
internal/requirements/helpers.go
internal/requirements/helpers_test.go
internal/terraform/local.go
pkg/ssmsession/ssmsession.go
pkg/term/interactive.go
pkg/term/runner.go
test-e2e/bastion_tunnel_test.go
test-e2e/ecs_apps_test.go
test-e2e/util.go

- refactor term and ssmsession modules
- fix `ize console` and `ize exec`
[![asciicast](https://asciinema.org/a/yNXQLru8MV7pU7maxEQWgIAuJ.svg)](https://asciinema.org/a/yNXQLru8MV7pU7maxEQWgIAuJ)

IZE-526 IZE-527: Refactor term and ssmsession modules

---

internal/schema/schema_test.go

- add a unit test for the Validate function

IZE-531 unit test for schema package

---

.github/workflows/run.unit-tests.yml
go.mod
go.sum
internal/aws/utils/utils.go
internal/commands/aws_profile_test.go
internal/commands/build.go
internal/commands/build_test.go
internal/commands/ize.go
internal/commands/status.go
internal/commands/status_test.go
internal/commands/terraform_test.go
internal/commands/testdata/build_valid.toml
internal/commands/testdata/status_valid.toml
internal/commands/testdata/tfenv_valid.toml
internal/commands/testing.go
internal/commands/tfenv.go
internal/commands/tfenv_test.go
internal/commands/tunnel_up_test.go
internal/config/config.go
internal/config/project.go

- added unit testing `ize status`
- added unit testing `ize gen tfenv`
- added unit testing `ize terraform`
- added unit testing `ize build`
- added unit testing `ize gen aws-profile`

Unit testing

---

internal/commands/status.go

- fixed show terraform version
[![asciicast](https://asciinema.org/a/mv6VQrR2PreKiHSwrqDDrQc4n.svg)](https://asciinema.org/a/mv6VQrR2PreKiHSwrqDDrQc4n)

fixed show terraform version

---

internal/manager/ecs/ecs.go
internal/manager/ecs/native.go

- added the ability to skip build and push the app
[![asciicast](https://asciinema.org/a/RSALYQln4KgXplGHsik7l1AqB.svg)](https://asciinema.org/a/RSALYQln4KgXplGHsik7l1AqB)
[![asciicast](https://asciinema.org/a/wUlvkXonyKBLMjH0AXo8X9Tlm.svg)](https://asciinema.org/a/wUlvkXonyKBLMjH0AXo8X9Tlm)
[![asciicast](https://asciinema.org/a/zlE30VKqH7ZSwKfZuoIpKdlpu.svg)](https://asciinema.org/a/zlE30VKqH7ZSwKfZuoIpKdlpu)

IZE-578 Added the ability to skip build and push the app

---

test-e2e/bastion_tunnel_test.go
test-e2e/ecs_apps_test.go
test-e2e/util.go

- add recovery function for e2e tests
[![asciicast](https://asciinema.org/a/fmFLLY9hNjsCniwTUJUbkYaFB.svg)](https://asciinema.org/a/fmFLLY9hNjsCniwTUJUbkYaFB)

add recovery function for e2e tests

---

internal/commands/ize.go
internal/config/project.go
internal/manager/ecs/ecs.go
internal/manager/ecs/ecs_test.go
internal/manager/ecs/native.go

- added unit tests for the ECS manager

IZE-568 Added unit tests for the ecs manager

---

internal/manager/serverless/native.go

- added support .nvmrc
[![asciicast](https://asciinema.org/a/MF8eTomlUF1C3fzLC9wQNGUzh.svg)](https://asciinema.org/a/MF8eTomlUF1C3fzLC9wQNGUzh)

IZE-604 added support .nvmrc

---

.github/workflows/run.unit-tests.yml
examples/ecs-apps-monorepo/.ize/env/testnut/goblin.tf
examples/ecs-apps-monorepo/.ize/env/testnut/squibby.tf

IZE-603 added junit report

---

website/components/mainPage/featuresBlock.js
website/components/sideBar/sideBar.module.css
website/components/welcomePageContent/welcomeContent.js
website/components/welcomePageContent/welcomeContent.module.css
website/main.css
website/pages/_app.js
website/pages/docs/index.js
website/pages/index.js
website/utilities/welcomePageHeaders.js

Ize 610 welcome page quickstart blocks

---

internal/commands/initialize.go
internal/commands/initialize_test.go

- added check TTY
- added `ize init` unit tests

IZE-551 test ize init

---

.github/workflows/release-prod.build-and-publish.yml

Enable docs creation

---

internal/commands/initialize.go

fixed check tty (build for windows)
[![asciicast](https://asciinema.org/a/X4YOOxoWNd8mVdHenCRFQdqmV.svg)](https://asciinema.org/a/X4YOOxoWNd8mVdHenCRFQdqmV)

fixed check tty (build for windows)

---

examples/ecs-apps-monorepo/.ize/env/testnut/main.tf
examples/ecs-apps-monorepo/.ize/env/testnut/variables.tf

- Upgrade examples/ecs-apps-monorepo to new terraform modules

Upgrade ecs-apps-monorepo

---

examples/bastion-tunnel-monorepo/.ize/env/testnut/output.tf
examples/ecs-apps-monorepo/.ize/env/testnut/output.tf

Add outputs

---

examples/ecs-apps-monorepo/.ize/env/testnut/goblin.tf
examples/ecs-apps-monorepo/.ize/env/testnut/squibby.tf

- enable nginx proxy in squibby

Add nginx proxy to squibby (ize-375)

---

go.mod
go.sum
internal/commands/down.go
internal/manager/alias/alias.go
internal/manager/alias/alias_test.go
internal/manager/ecs/ecs.go
internal/manager/ecs/ecs_test.go
internal/manager/ecs/native.go
internal/manager/manager.go
internal/manager/serverless/serverless.go
internal/manager/serverless/serverless_test.go

- when an ecs app is destroyed when an ecs app is destroyed
- updated pterm 
- added `autoApprove` parameter to destroy app
[![asciicast](https://asciinema.org/a/liyBbfIvbfRhEt3M7KZ2NGEgC.svg)](https://asciinema.org/a/liyBbfIvbfRhEt3M7KZ2NGEgC)

IZE-432 ize down squibby delete tasks definitions

---

internal/generate/generate.go

added using `id_rsa` by default when cloning over ssh protocol
[![asciicast](https://asciinema.org/a/B3AE3mG7qKvXZUff0hArf8cXs.svg)](https://asciinema.org/a/B3AE3mG7qKvXZUff0hArf8cXs)

IZE-683 add using id_rsa by default when cloning over ssh

---

internal/commands/ci.go

passed the project data to the generator

IZE-686 passed the project data to the generator

---

internal/terraform/local.go

added display version of terraform when downloaded
[![asciicast](https://asciinema.org/a/RFYzZW6GXVdYLl6joWgg3lmRn.svg)](https://asciinema.org/a/RFYzZW6GXVdYLl6joWgg3lmRn)

IZE-501 added display version of terraform when downloaded

---

internal/commands/up.go
internal/commands/up_apps.go
internal/commands/up_infra.go
internal/config/config.go
internal/manager/alias/alias.go
internal/manager/ecs/explain.go
internal/manager/manager.go
internal/manager/serverless/explain.go

- added `funcs` parameter to `Generate` function
- added `Explain` method for Managers
- added explain flag for ize up command
[![asciicast](https://asciinema.org/a/PHLzQehdYvHVSCCNqA37dtk39.svg)](https://asciinema.org/a/PHLzQehdYvHVSCCNqA37dtk39)

IZE-684 ize up sls app explain

---

internal/generate/generate.go

-  hide git output
[![asciicast](https://asciinema.org/a/oqbPK7GIBkRwccKGqM6hR6BCv.svg)](https://asciinema.org/a/oqbPK7GIBkRwccKGqM6hR6BCv)

IZE-689 hide git output

---

internal/commands/tfenv.go

disabled check tf state key
[![asciicast](https://asciinema.org/a/XzQaOAH3q3604JS7c2Vjf5aw6.svg)](https://asciinema.org/a/XzQaOAH3q3604JS7c2Vjf5aw6)

IZE-724 disabled check tf state key

---

internal/commands/tunnel_up.go
internal/config/infra.go
internal/schema/ize-spec.json

added ssh private/public key parameter in schema
[![asciicast](https://asciinema.org/a/dMgDinR1esYf5LvmZRy55sD84.svg)](https://asciinema.org/a/dMgDinR1esYf5LvmZRy55sD84)

IZE-674 added ssh private/public key parameter in schema

---

internal/commands/ize.go
internal/commands/nvm.go

fixed `ize nvm` bugs
[![asciicast](https://asciinema.org/a/ZUaXJ1Jq2XfoydNGLCm45K96U.svg)](https://asciinema.org/a/ZUaXJ1Jq2XfoydNGLCm45K96U)

IZE-702 IZE-703 IZE-706 ize nvm bugs

---

.github/workflows/run.e2e-tests.yml

- Enabled MacOS in e2e bastion test

Enable MacOS in e2e bastion test

---

.github/workflows/release-prod.build-and-publish.yml

- changed folder for docs: public to content

 IZE-731 Change folder for docs: public to content

---

internal/commands/console.go

added explain for `ize console`
[![asciicast](https://asciinema.org/a/FS5mRxAy3tXNMU8kNSf3rHDbr.svg)](https://asciinema.org/a/FS5mRxAy3tXNMU8kNSf3rHDbr)

IZE-699 added explain for `ize console`

---

internal/commands/tunnel_up.go

added termination of process that uses the port
[![asciicast](https://asciinema.org/a/WoJTp629ST7NNhGWjd502Vf9g.svg)](https://asciinema.org/a/WoJTp629ST7NNhGWjd502Vf9g)

IZE-654 added termination of process that uses the port

---

internal/commands/tunnel_up.go

added checking OS version of instance
[![asciicast](https://asciinema.org/a/RgYFEb8i2X7qfiCiqTfpSQjKU.svg)](https://asciinema.org/a/RgYFEb8i2X7qfiCiqTfpSQjKU)

IZE-695 added checking OS version of instance

---

.github/workflows/run.brew-and-apt-install-tests.yml

Add failure notification
